### ISSUE TITLE
sqlcipher

### ISSUE THREAD

**Issue by kalapalo** [karlseguin/zqlite.zig#10]
any way to access an encrypted (sqlcipher) sqlite db using zqlite ?

**Comment by karlseguin** [comment]
Never heard of it, but looking at the readme, it looks like if you can get it to link / build, it should work as-is?? You'll be able to use the PRAGMA key and PRAGMA rekey like any other statement.

Not 100% sure though.

**Comment by kalapalo** [comment]
SQLCipher is a super set of SQLite, has everything SQLite has plus encryption. And it works on non encrypted databases too.

I have followed your steps for for the amalgamation solution, so I downloaded sqlcipher and created the single sqlite3.c file and transferred it, along with the sqlite3.h to a lib directory under my project, and added your suggestions for the build.zig. It builds just fine.
First, it works on non encrypted databases. Then I tried on an encrypted one, it opens the database. Immediately after opening I use `conn.execNoArgs("PRAGMA key = 'mypass';")` what does not return any error, then when I try to insert something it fails saying `error: NotADB`, what by the way, is the same error SQLite emits if I try to open an encrypted db with it.

Sorry, this has nothing to do with zqlite. Am closing this now.
Please keep moving forward with zqlite. I really appreciate your minimalist wrapping approach.

**Comment by kalapalo** [comment]
For future searches ...
The solution was so obvious and I couldn't see it :(. No need of amalgamation files or anything else.
Since I have sqlite3 and sqlcipher installed by default in my system (Manjaro), I just need to link to the proper one.
For obvious reasons, in build.zig you link to sqlite3, so I just needed to change that to: `exe.linkSystemLibrary("sqlcipher");`
Working now :)
