### ISSUE TITLE
Zig fetch Installation not possible

### ISSUE THREAD

**Issue by WhiteElement** [karlseguin/zqlite.zig#7]
HI,
I'm pretty newish to the zig world so forgive me when I miss something obvious.

When trying to follow the installation steps, the zig fetch command (zig fetch --save git+https://github.com/karlseguin/zqlite.zig#master) fails, because the repo has no build.zig.zon file.

So I've been trying to manually add zqlite to my build.zig.zon but I could not get it to work either. This is my second time adding dependencies in zig and it's very possible that I am the problem.

Thanks in advance anyways

**Comment by karlseguin** [comment]
I added a build.zig.zon. 

But you should be able to add this to your file:

```
.zqlite = .{
    .url = "git+https://github.com/karlseguin/zqlite.zig?ref=master#4e95b4a13bff0c381d546753fcbe2d9a5f96c963",
    .hash = "12208eb54981192f3b30d045e5076615f08d86b5471f9f26d82a1f5bd59019d3ce4c",
}
```

**Comment by WhiteElement** [comment]
it's working now. Thank you very much. Looking forward to using this
